version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - dashnet

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile_db
    networks:
      - dashnet
    volumes:
      - "dbdata:/var/lib/mysql"
    secrets:
      - mysql_root
      - mysql_db
      - mysql_user
      - mysql_pw

networks:
  dashnet:

volumes:
  dbdata:

secrets:
  mysql_root:
    file: secrets/mysql_root_pw
  mysql_db:
    file: secrets/mysql_db
  mysql_user:
    file: secrets/mysql_user
  mysql_pw:
    file: secrets/mysql_pw
