FROM golang:1.16

WORKDIR /go/src/app

# test hack
# index.html is begging to be a template now
COPY frontend/public/index.html internal/server/web/

COPY go.mod go.sum main.go ./
COPY internal ./internal
RUN go install
ENV GIN_MODE=test

CMD ["go", "test" ,"./..."]
